### ISSUE TITLE
Problem with brew

### ISSUE THREAD

**Issue by giuseppetur** [KDAB/homebrew-tap#15]
Hello KDAB team,
I have the following error when I try to install something from your tap.

Actually three days ago the script was working but I had another issue to get your KDStateMachineEditor since the qt-5 compiling didn't work (hung on compiling) that's why I tried to update homebrew and your tap script.

```
brew search kdab
Error: /usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:5: syntax error, unexpected tIDENTIFIER, expecting keyword_end
...6bd66e0086227dc2af0b0afac973a4a"
...                               ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:6: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  head "https://github.com/KDAB/KDStateMachineEditor.git"
             ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:6: unknown regexp options - gthb
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:6: syntax error, unexpected tSTRING_BEG, expecting keyword_end
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:8: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  depends_on "qt5" => "with-d-bus"
                 ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:8: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  depends_on "qt5" => "with-d-bus"
                           ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:8: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:9: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  depends_on "graphviz"
                      ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:10: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  depends_on "cmake" => :build
                   ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:13: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system "cmake", ".", *std_cmake_args
                 ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:13: syntax error, unexpected tSTRING_BEG, expecting '('
    system "cmake", ".", *std_cmake_args
                       ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:14: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system "make"
                ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:15: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system "make", "install"
                ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:15: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system "make", "install"
                           ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:19: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system "make", "test"
                ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:19: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    system "make", "test"
                        ^
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:19: unterminated string meets end of file
/usr/local/Library/Taps/kdab/homebrew-tap/kdstatemachineeditor-qt5.rb:19: syntax error, unexpected end-of-input, expecting keyword_end
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:175:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/cmd/search.rb:167:in `block in search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:165:in `map'
/usr/local/Library/Homebrew/cmd/search.rb:165:in `search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:59:in `search'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by pasnox** [comment]
Looks like a ruby error inside your script.
Can u paste your changes ?

**Comment by pasnox** [comment]
Was an error in our latests commit - sorry.
Should be fixed now.
Just update brew again.

**Comment by winterz** [comment]
my bad. thanks for fixing.
