### ISSUE TITLE
[macOS high Sierra 10.13.2] Unable to 'make'

### ISSUE THREAD

**Issue by Pawel-Witkowski** [KDAB/homebrew-tap#17]
Brew is installed of course. Is it a problem with home-brew installer or I did something wrong? 
```
CPMC006:~ XXXX$ brew install gammaray-qt5
==> Installing gammaray-qt5 from kdab/tap
==> Installing dependencies for kdab/tap/gammaray-qt5: kdstatemachineeditor-qt5
==> Installing kdab/tap/gammaray-qt5 dependency: kdstatemachineeditor-qt5
==> Downloading https://github.com/KDAB/KDStateMachineEditor/archive/v1.2.3.tar.
Already downloaded: /Users/XXXX/Library/Caches/Homebrew/kdstatemachineeditor-qt5-1.2.3.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
==> make
Last 15 lines from /Users/XXXX/Library/Logs/Homebrew/kdstatemachineeditor-qt5/02.make:
                                                   ~~~~^~~~~
/tmp/kdstatemachineeditor-qt5-20180405-14484-1bdin26/KDStateMachineEditor-1.2.3/src/core/../../../../../../../private/tmp/kdstatemachineeditor-qt5-20180405-14484-1bdin26/KDStateMachineEditor-1.2.3/src/core/model/element.h:111:13: note: 'pos' declared here
    QPointF pos() const;
            ^
/usr/local/opt/qt/lib/QtCore.framework/Headers/qmetatype.h:1926:1: note: forward declaration of 'QPointF'
QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/usr/local/opt/qt/lib/QtCore.framework/Headers/qmetatype.h:110:20: note: expanded from macro 'QT_FOR_EACH_STATIC_CORE_CLASS'
    F(QPointF, 26, QPointF) \
                   ^
1 error generated.
make[2]: *** [src/core/CMakeFiles/kdstatemachineeditor_core.dir/kdstatemachineeditor_core_autogen/mocs_compilation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/core/CMakeFiles/kdstatemachineeditor_core.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/kdab/homebrew-tap/issues

/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x007f89cf473028> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by winterz** [comment]
I fixed it in the code.  not a brew problem.

I can either add a patch to the brew formula or release a minor bugfix.  I'll figure out what to do soon.

**Comment by Pawel-Witkowski** [comment]
Uh. Great : )When should we expect some fix?

**Comment by winterz** [comment]
try it now

**Comment by Pawel-Witkowski** [comment]
works like a charm now. Thanks for your help
